###Logear un usuario
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Idiarj",
    "password": "16012004d"
}


###Ver usuario logeado
GET http://localhost:3000/login

###Cerrar sesion
POST http://localhost:3000/logout

###Ver categorias
GET http://localhost:3000/pais


###Agregar producto
POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "Coca Cola",
    "precio": 10,
    "marca": "Lululemon",
    "categoria": "Clothing",
    "proveedor": "Proveedor1"
}

###Ver productos
GET http://localhost:3000/productos

